Areas/Candidate/Controllers/CandidateSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using JobPortal.Core;
using JobPortal.Core.Domain;
using JobPortal.Core.Repository;
using JobPortal.Web;

namespace JobPortal.Areas.Candidate.Controllers
{
    public class CandidateSearchController : Controller
    {
        
       private CandidateSearchModel _candidateSearchModel;
        
       private readonly  CandidateRepository _repository =new CandidateRepository();
       
       
        [Authorize]
        [HttpGet]
        public  ActionResult CandidateList()
        {
            HttpCookie cookie = HttpContext.Request.Cookies.Get(FormsAuthentication.FormsCookieName);
            if (cookie != null)
            {
                FormsAuthenticationTicket Ticket = FormsAuthentication.Decrypt(cookie.Value);
                int candidateId = int.Parse(Ticket.Name);

                _candidateSearchModel = new CandidateSearchModel();
                _candidateSearchModel.AddPersonal = new CandidatePersonal();
                _candidateSearchModel.AddPersonal.Experience = new Experience();
                _candidateSearchModel.AddPersonal.Education = new Education();
                _candidateSearchModel.AddPersonal.Skill = new Skill();
                _candidateSearchModel.AddPersonal.PageIndex = 0;

                _candidateSearchModel.PersonalList = _repository.CandidateSearch(_candidateSearchModel.AddPersonal);
                ViewBag.count = _candidateSearchModel.PersonalList.Count();

                return View(_candidateSearchModel);
            }
            return RedirectToAction("login", "Home");


        }
       [HttpPost]
        public ActionResult CandidateList(CandidateSearchModel candidate)
        {
           
           // candidate.AddPersonal = new CandidatePersonal();
            //candidate.AddPersonal.Experience = new Experience();
            //candidate.AddPersonal.Skill = new Skill();
            //candidate.AddPersonal.Education = new Education();
           // _candidateSearchModel=new CandidateSearchModel();
             //candidate.AddPersonal.PageIndex = 0;
            candidate.PersonalList = _repository.CandidateSearch(candidate.AddPersonal);
           // _candidateSearchModel.AddPersonal= candidate.AddPersonal;
           // _candidateSearchModel.AddPersonal.Skill = candidate.AddPersonal.Skill;
            //_candidateSearchModel.AddPersonal.Experience = candidate.AddPersonal.Experience;
           
            return View(candidate);

        }
       
      
        [HttpGet]
        public ActionResult CandidateDetail(int id)
        {
             CandidatePersonal cp = new CandidatePersonal();
               
             cp.CandidateList =_repository.GetCandidateRecord(id).ToList();
             cp.ExperienceList = _repository.GetExperienceRecord(id).ToList();
             cp.EducationList  = _repository.GetEducationRecord(id).ToList();
             cp.SkillList = _repository.GetSkillRecord(id).ToList();

            return View(cp) ;
        }

        public ActionResult Paging(int id, string what, string where, string funArea, string minimumExp)
        {
            CandidateSearchModel model = new CandidateSearchModel();
            model.AddPersonal = new CandidatePersonal();
            model.AddPersonal.Experience = new Experience();
            model.AddPersonal.Skill = new Skill();
            model.AddPersonal.Education = new Education();
            
            model.AddPersonal.PageIndex = id;
            model.AddPersonal.Skill.SkillTerm = what;
            model.AddPersonal.City = where;

            model.AddPersonal.Experience.FunctionalArea = funArea;
            model.AddPersonal.Experience.ExpYear = minimumExp;

            
            CandidateRepository _repository=new CandidateRepository();
          
            model.PersonalList = _repository.CandidateSearch(model.AddPersonal);
            
            
            return PartialView("ShortDetail", model);
        }

        [HttpGet]
        public ActionResult NewProfile()
        {
            return  View();
        }      
    }
}

Areas/Employer/Controllers/EmployerMessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using JobPortal.Areas.Employer.Models;
using JobPortal.Core;
using JobPortal.Core.Domain.User;

namespace JobPortal.Areas.Employer.Controllers
{
    public class EmployerMessageController : Controller
    {
        //
        // GET: /Employer/EmployerMessage/

        private EmployerVM _employerVm;
        private EmployerRepository _employerRepository;
        [Authorize]
        public ActionResult Index()
        {
            HttpCookie cookie = HttpContext.Request.Cookies.Get(FormsAuthentication.FormsCookieName);
            if (cookie != null)
            {
                FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(cookie.Value);
                int candidateId = int.Parse(ticket.Name);
                _employerVm = new EmployerVM();
                _employerRepository = new EmployerRepository();
                //_employerVm.PMs = _employerRepository.GetUnReadMessage(candidateId);
                _employerVm.MsgTitle = _employerRepository.GetMsgTitle(candidateId);
                return View("Index", _employerVm);
            }
            return View();
        }

        public ActionResult DisplayMsg(string title)
        {
            HttpCookie cookie = HttpContext.Request.Cookies.Get(FormsAuthentication.FormsCookieName);
            if (cookie != null)
            {
                FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(cookie.Value);
                int candidateId = int.Parse(ticket.Name);
                _employerVm = new EmployerVM();
                _employerRepository = new EmployerRepository();
                _employerVm.PMs = _employerRepository.GetUnReadMessage(candidateId,title);
                return PartialView("DisplayMsg",_employerVm);
            }
            Index();
            return View("Index");
        }

        public ActionResult DetailDiscussion(long id)
        {
            HttpCookie cookie = HttpContext.Request.Cookies.Get(FormsAuthentication.FormsCookieName);
            if (cookie != null)
            {
                FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(cookie.Value);
                int candidateId = int.Parse(ticket.Name);
                _employerVm = new EmployerVM();
                _employerRepository = new EmployerRepository();
                _employerVm.PMs = _employerRepository.AllDiscussionMsg(id);
                return PartialView("DisplayDisscuss",_employerVm);
            }
            Index();
            return View("Index");
        }

    }
}

Areas/Job/Controllers/JobSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using JobPortal.Core;
using JobPortal.Areas.Job.Models;
using JobPortal.Core.Repository;

namespace JobPortal.Areas.Job.Controllers
{
    using Core.Domain.User;

    public class JobSearchController : Controller
    {
        private SearchRepository _searchRepository;
        private FavRepository _favRepository;
        private EmployerRepository _employerRepository;
        private JobSearchVM _jobSearchVm;

        public ActionResult Index()
        {
            return View();
        }

        /*====== This method fetch Jobs As per Keyword Entered If Keywords are null then it will fetch all records */
        [HttpPost]
        public ActionResult Index(Core.Job job)
        {
            _searchRepository = new SearchRepository();
            _favRepository = new FavRepository();
            _jobSearchVm = new JobSearchVM();

            if(job.KeyTerm != null || job.Country!= null)
            {
                var recentSearch = new RecentSearch(job.KeyTerm,job.Country);
                recentSearch.RecentSearches = new List<RecentSearch>();
                recentSearch.RecentSearches.Add(new RecentSearch(job.KeyTerm,job.Country));

                if (Session["RecentSearch"] != null)
                {
                    var sessionItems = (List<RecentSearch>)Session["RecentSearch"];
                    
                    recentSearch.RecentSearches.AddRange((List<RecentSearch>)Session["RecentSearch"]);
                    bool hasKeyword = false; bool hasLocation=false;
                    hasKeyword = sessionItems.Any(has => has.KeyTerms == recentSearch.KeyTerms);
                    hasLocation = sessionItems.Any(has => has.Location == recentSearch.Location);
                    if (hasKeyword == false || hasLocation == false)
                    {
                        Session["RecentSearch"] = (List<RecentSearch>)recentSearch.RecentSearches;
                    }
                }
                else
                {
                    //recentSearch.RecentSearches.Add(new RecentSearch(job.KeyTerm,job.KeyTerm));
                    Session["RecentSearch"] = (List<RecentSearch>) recentSearch.RecentSearches;
                }
            }
            _jobSearchVm.Jobs = _searchRepository.Search(job,2);
            _jobSearchVm.Job = job;
            
            /*============ Data To Use In Other Method ==============*/
            TempData.Clear();
            TempData["ListofJobs"] = _jobSearchVm.Jobs;
            //Session["ListofJobs"] = _jobSearchVm.Jobs;
            /*=======================================================*/

            if (HttpContext != null)
            {
                HttpCookie cookie = HttpContext.Request.Cookies.Get(FormsAuthentication.FormsCookieName);
                if (cookie != null)
                {
                    FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(cookie.Value);
                    int candidateId = int.Parse(ticket.Name);
                    if(candidateId !=0)
                    {
                        _jobSearchVm.FavJobs = _favRepository.GetAll(candidateId);
                    }
                }
            }
            return View(_jobSearchVm);
        }
        
        /*====== This method fetch Jobs As per Keyword Entered Using Ajax Request If Keywords are null then it will fetch all records Ajax Request */
        [HttpPost]
        public ActionResult AjaxSearch(Core.Job job)
        {        
            _searchRepository = new SearchRepository();        
            _jobSearchVm = new JobSearchVM();        
            _favRepository = new FavRepository();        
            if (job.KeyTerm != null || job.Country != null)        
            {        
                var recentSearch = new RecentSearch                               
                {                               
                    RecentSearches = new List<RecentSearch>{new RecentSearch(job.KeyTerm, job.Country)}                               
                };        
                if (Session["RecentSearch"] != null)        
                {        
                    Session.Add("RecentSearch", recentSearch.RecentSearches);        
                }        
                else        
                {        
                    Session["RecentSearch"] = (List<RecentSearch>) recentSearch.RecentSearches;        
                }        
            }        
            _jobSearchVm.Jobs = _searchRepository.Search(job, 2);        
            _jobSearchVm.Job = job;
            TempData.Clear();
            TempData["ListofJobs"] = _jobSearchVm.Jobs;
            return PartialView("Detail",_jobSearchVm);
        }


        /*====== This Action is used for Water Text ======*/
        /*public ActionResult Lookup(string id)
        {
            _searchRepository = new SearchRepository();
            _jobSearchVm = new JobSearchVM();
            _jobSearchVm.BasicSearches = _searchRepository.Keyterms();
            var retval = _jobSearchVm.BasicSearches
                .Where(x => x.StartsWith(id))
                .OrderBy(x => x)
                .Take(3)
                .Select(r => new { Tag = r });

            var tagNames = (from p in _jobSearchVm.BasicSearches where p.Contains(id) select p).Distinct().Take(3);

            string content = string.Join<string>("\n", tagNames);
            //return Content(content);
            return Json(content);
        }*/


        /*====== Each Page Shows five Jobs Per Page By Using this action candidate can see other jobs ======*/
        public ActionResult PageIndex(int id, string what, string where, string sortBy)
        {
            _favRepository = new FavRepository();
            _searchRepository = new SearchRepository();
            var j = new Core.Job {KeyTerm = what, Country = @where, OrderBy = sortBy, PageIndex = id};
            _jobSearchVm = new JobSearchVM {Jobs = _searchRepository.Search(j, 2), Job = j};
            TempData.Clear();
            TempData["ListofJobs"] = _jobSearchVm.Jobs;
            return PartialView("Detail",_jobSearchVm);
        }


        /*====== This Action shows a Detail Description about a particular job ======*/
        [HttpGet]
        public ActionResult JobDetail(int id)
        {
            _jobSearchVm = new JobSearchVM();
            _employerRepository = new EmployerRepository();
            _jobSearchVm.Job = new Core.Job {Emplyer = new Employer()};
            _searchRepository = new SearchRepository();
            _jobSearchVm.Job = _searchRepository.SearchJobbyId(id);
            _jobSearchVm.Job.Emplyer = _employerRepository.GetEmployerById(_jobSearchVm.Job.Emplyer.EmployerId);
            return View(_jobSearchVm);
        }


        /*====== User click on keyterm as per that key term search from database ======*/
        public virtual ActionResult SearchOnKeyterm(string id)
        {
            var job = new Core.Job {Emplyer = new Employer(), KeyTerm = id};
            Index(job);
            return View("Index");
        }


        /*====== User click on ViewAll Job this action will perform ======*/
        public ActionResult GetAllJobs()
        {
            var job = new Core.Job {Emplyer = new Employer()};
            Index(job);
            return View("Index");
        }


        /*====== User click on recent search jobs then this job will display previous search ======*/
        public ActionResult RecentSearch(string pKeyTerm,string pLocation)
        {
            var job = new Core.Job {KeyTerm = pKeyTerm, Country = pLocation};
            Index(job);
            return View("Index");
        }


        /*====== This action used to add jobs to favorite job list It is Only For Autorised user ======*/
        [Authorize]
        public ActionResult FavJob(int jid,string jobTitle,string company)
        {
            if (HttpContext != null)
            {
                HttpCookie cookie = HttpContext.Request.Cookies.Get(FormsAuthentication.FormsCookieName);
                if (cookie != null)
                {
                    FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(cookie.Value);
                    int candidateId = int.Parse(ticket.Name);

                    var favJob = new FavJob {Job = new Core.Job(), MainUserId = new MainUser()};
                    _jobSearchVm = new JobSearchVM();
                    _favRepository = new FavRepository();
                    var uow = new UnitOfWork();

                    favJob.Job.Id = jid;
                    favJob.MainUserId.Mid = candidateId;
                    favJob.JobTitle = jobTitle;
                    favJob.CompanyName = company;

                    _favRepository.AddFavoritejob(favJob,uow);
                    uow.Commit();
                
                    _jobSearchVm.FavJobs = _favRepository.GetAll(candidateId);
                }
            }
            //_jobSearchVm = new JobSearchVM();
            //_jobSearchVm.Jobs = _searchRepository.Search(j, 2);
            //_jobSearchVm.Job = j;
            //TempData.Clear();
            //TempData["ListofJobs"] = _jobSearchVm.Jobs;
            return PartialView("FavoriteJobs", _jobSearchVm);
        }


        /*====== This action used to Remove jobs from favorite job list It is Only For Autorised user ======*/
        [Authorize]
        public ActionResult RemoveFavoriteJob(int jobId,Boolean removeType)
        {
            if (HttpContext != null)
            {
                HttpCookie cookie = HttpContext.Request.Cookies.Get(FormsAuthentication.FormsCookieName);
                if (cookie != null)
                {
                    FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(cookie.Value);
                    int candidateId = int.Parse(ticket.Name);

Views/Shared/Header.cshtml
<div class="form-inline">
    <div class="employerHeader employerFont  Post-Padding">
        <div class="span4">
            <h6 style="font-size: medium">Version System Pvt.Ltd.</h6>
        </div>
        <div class="span5">
            <h6 style="font-size: medium">Personal Messages</h6>
        </div>
        <h6 style="font-size: medium">Rajkot,Gujarat</h6>
    </div>
</div>

Views/Shared/_Layout.cshtml
@using System.Web.UI.WebControls
@using MvcSiteMapProvider.Web.Html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <title>@ViewBag.Title</title>
    <meta name="title" content="Classifieds">
    <meta name="description" content="classifieds">
    <meta name="keywords" content="classifieds">
    <meta name="generator" content="Classifieds 0.1">
    <script type="text/javascript">
        //function ClearyHistory() {
        //    javascript: window.history.forward(-1);
        //    window.history.forword(-1);
        //}
        //window.history.forward(1);
        //document.attachEvent("onkeydown", my_onkeydown_handler);
        //function my_onkeydown_handler() {
        //    switch (event.keyCode) {
        //        case 116: // F5;
        //            event.returnValue = false;
        //            event.keyCode = 0;
        //            window.status = "We have disabled F5";
        //            break;
        //    }
        //}

        //function changeHashOnLoad() {
        //    window.location.href += "#";
        //    setTimeout("changeHashAgain()", "50");
        //}

        //function changeHashAgain() {
        //    window.location.href += "1";
        //}

        //var storedHash = window.location.hash;
        //window.setInterval(function () {
        //    if (window.location.hash != storedHash) {
        //        window.location.hash = storedHash;
        //    }
        //},
        //50);

        //function noBack() {
        //    window.history.forward();
        //}
        //noBack();
        //window.onload = noBack;
        //window.onpageshow = function (evt) { if (evt.persisted) noBack(); };
        //window.onunload = function () { void (0); };
    </script>
    @*  -----    CSS Files    -----   *@
    @*<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">*@
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" type="text/css" />
    @*<link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" />*@
    <link href="@Url.Content("~/Content/jquery.tagbox.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap-responsive.min.css")" rel="stylesheet" />
    @*  -----   Javascript Files    ----- *@
    <script src="../../Scripts/jquery-1.4.4.min.js"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-1.8.2.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    @*<script src="https://code.jquery.com/jquery-3.4.1.js" type="text/javascript" crossorigin="anonymous"></script>*@
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    @*<script src="@Url.Content("~/Content/JS/ckeditor/config.js")"></script>
    <script src="@Url.Content("~/Content/JS/ckeditor/ckeditor.js")"></script>*@
    <script src="../Content/JS/ckeditor/ckeditor.js"></script>
    <script src="../Content/JS/ckeditor/config.js"></script>    
    <script src="@Url.Content("~/Scripts/MicrosoftAjax.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/MicrosoftMvcAjax.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    @*<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" crossorigin="anonymous"></script>*@
    <script src="@Url.Content("~/Scripts/jquery.tagbox.js")"></script>
    @*<script src="@Url.Content("~/Scripts/bootstrap.js")" type="text/javascript"></script>*@
</head>

<body data-spy="scroll" data-target=".subnav" data-offset="50">

    <div class="meta container">
        <div class="row">
            <div class="col-md-12">
                @*<div style="width: 200px;margin-left: 400px">*@
                @{
                    if (Request.Cookies.Get("UserName") != null)
                    {
                        var httpCookie = Request.Cookies.Get("UserName");
                        if (httpCookie != null)
                        {
                            var userName = httpCookie.Value;
                            string displayName = null;
                            //<p style="font-size: 12px"><i class="icon-user icon-white"></i> @userName @Html.ActionLink("Logout", "Logout",
                            //                                                                                           new {area = "", Controller = "Home"}@*,new {onclick = "changeHashOnLoad();"}*@)</p>
                            foreach (var c in userName)
                            {
                                if (c != '.')
                                {
                                    displayName = displayName + c;
                                }
                                else { break; }
                            }
                            <a style="font-size: 12px;color: white;padding-left: 500px;text-decoration: none" href="@Url.Action("Logout", new { Area = "", Controller = "Home" })"><i class="icon-user icon-white"></i><b>&nbsp;Hi, @displayName</b> &nbsp;&nbsp;&nbsp; Logout &nbsp;<i class="icon-off icon-white"></i></a>
                        }
                    }
                    else
                    {
                        @*<p>Recruiters:  @Html.ActionLink("Login", "Login", new {area = "", Controller = "Home"}) or
                            @Html.ActionLink("Register Now", "RegisterUser", new {area = "", Controller = "Home"})</p>*@
                        <a style="font-size: 12px;color: white;padding-left: 10px;text-decoration: none;float: right;" href="@Url.Action("Login", new { Area = "", Controller = "Home" })"><i class="icon-user icon-white"></i>&nbsp;Login</a>
                        <a style="text-decoration: none">&nbsp;&nbsp;&nbsp;&nbsp;</a>
                        <a style="font-size: 12px;color: white;text-decoration: none;float: right;" href="@Url.Action("RegisterUser", new { Area = "", Controller = "Home" })">Register User</a>
                    }
                }
                @*</div>*@
                @*<div class="metalinks">
                        <a href="#"><img src=@Url.Content("~/Content/themes/base/images/meta1.gif") alt="" width="15" height="14" /></a>
                        <a href="@Url.Action("Index","Home",new {area = "",Controller="Home"})"><img src=@Url.Content("~/Content/themes/base/images/meta1.gif") alt="" width="15" height="14" /></a>
                        <a href="#"><img src=@Url.Content("~/Content/themes/base/images/meta2.gif") alt="" width="17" height="14" /></a>
                        <a href="#"><img src=@Url.Content("~/Content/themes/base/images/meta3.gif") alt="" width="17" height="14" /></a>
                        <a href="#"><img src=@Url.Content("~/Content/themes/base/images/meta4.gif") alt="" width="15" height="14" /></a>
                    </div>*@
            </div>
        </div>
    </div>
    <div id="header" class="container">
        <div class="row">
            <div class="col-md-3">
                <a href="@Url.Action("Index", "Home", new { area = "", Controller = "Home" })" class="logo col-md-12">
                    <img src=@Url.Content("~/Content/themes/base/images/logo.jpg") alt="setalpm" width="149" height="28" />
                    <span class="slogan">Your Key to Success</span>
                </a>
            </div>
            <div class="MainMenu col-md-9" style="float: left">
                <ul>
                    <li>
                        <a href="@Url.Action("Index", "Home", new { area = "", Controller = "Home" })"><i class="icon-home"></i>&nbsp;Home</a>
                    </li>
                    <li>
                        <a href="#"><i class="icon-briefcase"></i>&nbsp;Employer</a>
                        <ul>
                            <li><a href="@Url.Action("CandidateList", "CandidateSearch", new { area = "Candidate", Controller = "CandidateSearch" })"><i class="icon-search"></i>&nbsp;Candidate Search </a></li>
                            <li><a href="@Url.Action("JobPost", "JobPost", new { Area = "Job", Controller = "JobPost" })"><i class="icon-fire"></i>&nbsp;Post a Job</a></li>
                            <li><a href="@Url.Action("Index", "EmployerAccount", new { Area = "Employer", Controller = "EmployerAccount" })"><i class="icon-list"></i>&nbsp;My Jobs</a></li>
                            <li><a href="@Url.Action("Index", "EmployerMessage", new { Area = "Employer", Controller = "EmployerMessage" })"><i class="icon-envelope"></i>&nbsp;Messages</a></li>
                            <li><a href="#"><i class="icon-glass"></i>&nbsp;Pre-Purchasing</a></li>
                            <li><a href="@Url.Action("GetAllJobs", "JobSearch", new { Area = "Job", Controller = "JobSearch" })"><i class="icon-user"></i>&nbsp;JobSeeker >></a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="icon-user"></i>&nbsp;Job Seekers</a>
                        <ul>
                            <li><a href="#"><i class="icon-search"></i>&nbsp;Search Job</a></li>
                            <li><a href="#"><i class="icon-folder-open"></i>&nbsp;My Profile</a></li>
                            <li><a href="#"><i class="icon-gift"></i>&nbsp;Match Jobs</a></li>
                            <li><a href="#"><i class="icon-list-alt"></i>Applied Jobs</a></li>
                            <li><a href="#"><i class="icon-envelope"></i>&nbsp;Messages</a></li>
                            <li><a href="@Url.Action("CandidateList", "CandidateSearch", new { area = "Candidate", Controller = "CandidateSearch" })"><i class="icon-briefcase"></i>&nbsp;Employer >></a></li>
                        </ul>
                    </li>
                    <li><a href="#"><i class="icon-road"></i>&nbsp;Contect Us</a></li>
                    <li><a href="#"><i class="icon-question-sign"></i>&nbsp;Help</a></li>
                </ul>
            </div>
        </div>
    </div>

    @*<div class="row" style="padding-left: 40px;padding-top: 19px">
           @Html.MvcSiteMap().SiteMapPath()
        </div>*@

    @RenderBody()

    <div id="footer">
        Copyright &copy;. All rights reserved. Design by <a href="http://www.bestfreetemplates.info" target="_blank" title="Free CSS templates">version systems</a>
    </div>
</body>
</html>