Areas/Profile/Models/ProfileResume.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobPortal.Core.Domain.User;

namespace JobPortal.Web.Areas.Profile.Models
{
    public class ProfileResume
    {

        public Core.Resume AddResume { get; set; }
        public Core.CandidatePersonal Candidate { get; set; }

        public Core.CandidatePersonal EditCandidate { get; set; }
        public Core.Experience EditExperience { get; set; }
        public Core.Education EditEducation { get; set; }
        public Core.Skill EditSkill { get; set; }
        public Core.Resume EditResume { get; set; }

        public Core.Job Job { get; set; }
       

        public List<Core.CandidatePersonal> CandidatePersonals { get; set; }
        public List<Core.Experience> Experiences { get; set; }
        public List<Core.Education> Educations { get; set; }
        public List<Core.Skill> Skills { get; set; }
        public List<Core.Resume> Resumes { get; set; }

        public List<Core.Job> MatchJobs { get; set; }

        public List<PersonalMessage> PersonalMessages { get; set; }

        public PersonalMessage Personal { get; set; }

        public List<string> JobTitle { get; set; }
    }
}

Areas/Profile/Controllers/MyMessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using JobPortal.Areas.Employer.Models;
using JobPortal.Core;
using JobPortal.Web.Areas.Profile.Models;

namespace JobPortal.Web.Areas.Profile.Controllers
{
    public class MyMessageController : Controller
    {
        //
        // GET: /Profile/MyMessage/
        
        private EmployerRepository _employerRepository;
        private ProfileResume _profileResume; 
        [Authorize]
        [HttpGet]
        public ActionResult Index()
        {
            HttpCookie cookie = HttpContext.Request.Cookies.Get(FormsAuthentication.FormsCookieName);

            if (cookie != null)
            {
                FormsAuthenticationTicket Ticket = FormsAuthentication.Decrypt(cookie.Value);
                int candidateId = int.Parse(Ticket.Name);
                
                _employerRepository=new EmployerRepository();
                _profileResume=new ProfileResume();
                _profileResume.JobTitle=_employerRepository.GetJobTitle(candidateId);
                return PartialView("Index",_profileResume);
            }
            return View();
        }
        [Authorize]
        public ActionResult ShowMsg(string title)
        {

            HttpCookie cookie = HttpContext.Request.Cookies.Get(FormsAuthentication.FormsCookieName);

            if (cookie != null)
            {
                FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(cookie.Value);
                int candidateId = int.Parse(ticket.Name);

                _employerRepository = new EmployerRepository();
                _profileResume = new ProfileResume();
                _profileResume.PersonalMessages = _employerRepository.GetUnreadCandidateMessage(candidateId, title);
                //_profileResume.JobTitle = _employerRepository.GetJobTitle(candidateId);
                return PartialView("ShowMsg",_profileResume);
            }
            return PartialView();
        }
        public ActionResult DetailShowMsg(int id)
        {
            HttpCookie cookie = HttpContext.Request.Cookies.Get(FormsAuthentication.FormsCookieName);
            if (cookie != null)
            {
                FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(cookie.Value);
                int candidateId = int.Parse(ticket.Name);
                _profileResume=new ProfileResume();
                _employerRepository = new EmployerRepository();
                _profileResume.PersonalMessages = _employerRepository.AllShowMsg(id);
                return PartialView("DetailShowMsg", _profileResume);
            }
            return PartialView();
        }

        public ActionResult SentNewMessage(ProfileResume model)
        {
            HttpCookie cookie = HttpContext.Request.Cookies.Get(FormsAuthentication.FormsCookieName);
            if (cookie != null)
            {
                FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(cookie.Value);
                int candidateId = int.Parse(ticket.Name);
                _profileResume = new ProfileResume();
                _employerRepository = new EmployerRepository();
               // _profileResume.PersonalMessages = _employerRepository.AllShowMsg();
                return PartialView("DetailShowMsg", _profileResume);
            }
            return null;
        }

    }
}

Areas/Profile/Controllers/MyProfileController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web;
using System.Web.Security;
using JobPortal.Core.Domain;
using JobPortal.Core.Domain.User;
using JobPortal.Web;
using JobPortal.Core;
using JobPortal.Web.Areas.Profile.Models;


namespace JobPortal.Web.Areas.Profile.Controllers
{
    public class MyProfileController : Controller
    {
        
     
        private CandidateRepository _candidateRepo;
            
        [Authorize]
        [HttpGet]
        public ActionResult RegisterProfile()
        {
            HttpCookie cookie = HttpContext.Request.Cookies.Get(FormsAuthentication.FormsCookieName);
            if (cookie != null)
            {
                FormsAuthenticationTicket Ticket = FormsAuthentication.Decrypt(cookie.Value);
                int candidateId = int.Parse(Ticket.Name);
            
        
            //first check if user is login or not ,if user is login then check that user is registration completed or not
           _candidateRepo=new CandidateRepository();
           
            long key= _candidateRepo.CheckRegistration(candidateId);
            
                
           
            ProfileResume mResume = new ProfileResume(); 

            if (key != 0 )
            {
                mResume.Candidate = new CandidatePersonal();
                mResume.Candidate.Experience =new Experience();
                mResume.Candidate.Education=new Education();
                mResume.Candidate.Skill=new Skill();
                mResume.Candidate.Resume=new Resume();

                mResume.Candidate.Experience.MainUser = new MainUser();
                mResume.Candidate.Experience.MainUser.Mid = candidateId; 

                mResume.Candidate.Education.MainUser=new MainUser();
                mResume.Candidate.Education.MainUser.Mid = candidateId;

                mResume.Candidate.Skill.MainUser=new MainUser();
                mResume.Candidate.Skill.MainUser.Mid = candidateId;
 
                mResume.Candidate.Resume.MainUser=new MainUser();
                mResume.Candidate.Resume.MainUser.Mid = candidateId;

                mResume.CandidatePersonals = _candidateRepo.GetCandidateRecord(candidateId).ToList();
                mResume.Experiences = _candidateRepo.GetExperienceRecord(candidateId).ToList();
                mResume.Educations = _candidateRepo.GetEducationRecord(candidateId).ToList();
                mResume.Skills = _candidateRepo.GetSkillRecord(candidateId).ToList();
                mResume.Resumes = _candidateRepo.GetResumeRecord(candidateId).ToList();

                return View("Profile", mResume);
            }
            else
            {
               
                mResume.Candidate =new CandidatePersonal();
                mResume.Candidate.MainUser =new MainUser();
                mResume.Candidate.MainUser.Mid = candidateId;
                mResume.Candidate.CreatedOn = DateTime.Now;
                mResume.Candidate.UpdatedOn = DateTime.Now;

                return View(mResume);    
            }

            }
            return null;
        }
        public void UpdateDate(long id)
        {
            Core.CandidatePersonal candidate=_candidateRepo.FindDateId(id);
            candidate.SetUpdateOn();
            _candidateRepo.ChangeDate(candidate);

        }
        [HttpGet]
        public ActionResult Edit(long id)
        {
            _candidateRepo=new CandidateRepository();
            var ProfileVM = new ProfileResume {EditCandidate = _candidateRepo.UpdateCandidateId(id)};
            return PartialView("Edit",ProfileVM);
        }
        [HttpPost]
        public  ActionResult Edit(ProfileResume model)
        {
            _candidateRepo=new CandidateRepository();
            var uow = new UnitOfWork();
           
            if (model.EditCandidate != null)
            {
             
                _candidateRepo.UpdateCandidate(model.EditCandidate,uow);
                if (uow.Commit())
                {
                    UpdateDate(model.EditCandidate.MainUser.Mid);
                    this.ShowMessage(MessageType.Success, "Candidate Personal detail has been changed.");
                }
                else
                {
                    this.ShowMessage(MessageType.Error, uow.ErrorMessage);
                }
            }
            else if(model.EditExperience !=null)
            {
                
                _candidateRepo.UpdateExperience(model.EditExperience,uow);
          
                if (uow.Commit())
                {
                    UpdateDate(model.EditExperience.MainUser.Mid);

                    this.ShowMessage(MessageType.Success, "Candidate Experience detail has been changed.");
                }
                else
                {
                    this.ShowMessage(MessageType.Error, uow.ErrorMessage);
                }
            }
            else if(model.EditEducation !=null)
            {
                _candidateRepo.UpdateEducation(model.EditEducation, uow);
                if(uow.Commit())
                {
                    UpdateDate(model.EditEducation.MainUser.Mid);
                    this.ShowMessage(MessageType.Success, "Candidate Education detail has been changed.");
                    
                }
                else
                {
                    this.ShowMessage(MessageType.Error, uow.ErrorMessage);
                }
            }
            else if(model.EditSkill !=null)
            {
                _candidateRepo.UpdateSkill(model.EditSkill, uow);

                if (uow.Commit())
                {
                    UpdateDate(model.EditSkill.MainUser.Mid);
                    this.ShowMessage(MessageType.Success, "Candidate Skill detail has been changed.");
                }
                else
                {
                    this.ShowMessage(MessageType.Error, uow.ErrorMessage);
                }
               
            }
           else if(model.EditResume !=null)
            {
                if (model.EditResume.Photo != null)
                {
                        
                    string path = @"D:\Temp\";

                   /* if (model.EditResume.Photo.ContentLength > 190240)
                    {
                        ModelState.AddModelError("photo", "The size of the file should not exceed 10 KB");
                        return View();
                    }*/
                    var supportedTypes = new[] { "jpg", "jpeg", "png", "txt", "doc","docx", "pdf" };
                    model.EditResume.FileExtension = System.IO.Path.GetExtension(model.EditResume.Photo.FileName).Substring(1);
                    model.EditResume.FileName = model.EditResume.Photo.FileName;

                    if (!supportedTypes.Contains(model.EditResume.FileExtension))
                    {
                        ModelState.AddModelError("photo", "Invalid type. Only the following types (jpg, jpeg, png) are supported.");
                        //_jobSearch.JobDetail(j.Id);
                        //        //return View();
                    }
                    //   csVM.AddResume.Photo.SaveAs(path + csVM.AddResume.Photo.FileName);
                    //  path = csVM.AddResume.Photo.InputStream.ToString();
                    MemoryStream target = new MemoryStream();
                    model.EditResume.Photo.InputStream.CopyTo(target);
                    model.EditResume.FileData = target.ToArray();

                   // Core.Resume resume = _candidateRepo.ChangeResume(model.EditResume.Rid);
                    //_candidateRepo.DeleteOldResume(resume);

                    _candidateRepo.ChangeResume(model.EditResume,uow);
                    if (uow.Commit())
                    {
                        UpdateDate(model.EditResume.MainUser.Mid);
                        this.ShowMessage(MessageType.Success, "Candidate resume has been changed.");

                    }
                    else
                    {
                        this.ShowMessage(MessageType.Error, uow.ErrorMessage);
                    }

                }

            } 
            
            
            return RedirectToAction("RegisterProfile");

        }
        [HttpGet]
        public ActionResult EditExperience(long id)
        {
            _candidateRepo=new CandidateRepository();
            var profileVM = new ProfileResume { EditExperience = _candidateRepo.UpdateExperienceId(id) };
            
            return PartialView("Edit",profileVM);
        }
      
        [HttpGet]
        public ActionResult EditEducation(long id)
        {
            _candidateRepo = new CandidateRepository();
            var profileVM = new ProfileResume {EditEducation = _candidateRepo.UpdateEducationId(id)};
            return PartialView("Edit",profileVM);
        }
     
        
        public ActionResult EditSkill(long id)
        {
            _candidateRepo = new CandidateRepository();
            var profileVM = new ProfileResume {EditSkill  = _candidateRepo.UpdateSkillId(id)};
            return PartialView("Edit",profileVM);
        }
      
       
       public  ActionResult ChangeResume(long id)
       {
           _candidateRepo = new CandidateRepository();
           var profileVM = new ProfileResume {EditResume = _candidateRepo.ChangeResume(id)};
           return PartialView("Edit", profileVM);
       }
     
        public ActionResult DeleteExperience(long id)
        {
            _candidateRepo = new CandidateRepository();
            var uow = new UnitOfWork();
            Core.Experience experience = _candidateRepo.UpdateExperienceId(id);
            _candidateRepo.RemoveExperience(experience,uow);
            if (uow.Commit())
            {
                this.ShowMessage(MessageType.Success, "Candidate  Experience has been deleted.");
            }
            else
            {
                this.ShowMessage(MessageType.Error, uow.ErrorMessage);

Areas/Profile/Views/MyProfile/ApplyEdit.cshtml
@using MvcContrib.FluentHtml
@model JobPortal.Web.Areas.Profile.Models.ProfileResume
@{
    Html.EnableUnobtrusiveJavaScript(true);
     HtmlHelper.ClientValidationEnabled = true;
}   
 
<style type="text/css"> 
    #newed
    {
        display:none
    }
</style>

<script type="text/javascript">
    $(document).ready(function () {
        $("#default").click(function () {
            $("#newed").hide();

        });
        $("#new").click(function () {
            $("#newed").show();

        });
    });
</script>
<script>

    $('#frmName').removeData("validator");
    $('#frmName').removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse('#frmName');
</script>

     @using (Html.BeginForm("ApplyEdit", "MyProfile", FormMethod.Post, new {enctype = "multipart/form-data" ,id="frmName"}))
     {
       <div class="span3">  
                         @Html.HiddenFor(m => m.EditResume.Apply.JobId.Id)
                         @Html.HiddenFor(m=>m.EditResume.Apply.CandidateId.Mid)
                        
                                <table border="0"  style="width:1500px; margin-left:30px " >
                                <tr><td style="font-size:12px ;width:100px  ; font: bold">
                                        Select Resume to Apply::       
                                    </td>
                                    <td style="width:1000px"></td>
                                </tr> 
                                <tr><td></td> 
                                    <td style="width:1000px" >
                                        @Html.RadioButton("ABC","YES",true,new{id="default"}) Default Resume 
                                        
                                    </td>
                                </tr>
                                <tr> <td></td>
                                    <td style="width:1000px">
                                        @Html.RadioButton("ABC","NO",new{id="new"}) Change Resume       
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                    </td>
                                    <td style="width:1000px " id="newed">
                                        @Html.TextBoxFor(m => m.EditResume.Photo,new{ type = "file" }) 
                                        @Html.ValidationMessageFor(m=>m.EditResume.Photo)
                                    </td>
                                </tr>
                                    <tr>    @Html.TextAreaFor(m => m.EditResume.Apply.Coverletter)
                                            @Html.ValidationMessageFor(m=>m.EditResume.Apply.Coverletter)

                                    </tr>
                            </table> 
                          <div class="modal-footer">
                            @this.SubmitButton("Save").Class("btn btn-primary")
                            @this.Button("Close").Class("btn").Attr("data-dismiss", "modal").Attr("aria-hidden", "true")
                        </div>

                     
        </div>
     }

Areas/Profile/Views/MyProfile/Edit.cshtml
@using JobPortal.Core
@using MvcContrib.FluentHtml
@model JobPortal.Web.Areas.Profile.Models.ProfileResume
@{
    
    ExpYearList eyl = new ExpYearList();
    
    Html.EnableUnobtrusiveJavaScript(true);
    HtmlHelper.ClientValidationEnabled = true;
}
@*<style>
 #Experience
{
      display:none
}
</style>*@
<script>
    $(document).ready(function () {
        $("#Experienced").click(function ()
        {
            alert("expe1");
            $("#Experience").slideDown("fast");
            alert("expe2");

        });
        $("#Freshered").click(function ()
        {
           $("#Experience").slideUp("fast");
        });

    });
</script>
<script>
    
    $('#frmName').removeData("validator");
    $('#frmName').removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse('#frmName');
</script>
@if (Model.EditCandidate != null)
{
    using (Html.BeginForm("Edit", "MyProfile", FormMethod.Post, new { Area = "Profile", id="frmName" }))
    {
        
        <div class="span5">
            @Html.HiddenFor(m => m.EditCandidate.Id)
            @Html.HiddenFor(m => m.EditCandidate.MainUser.Mid)

            @Html.TextBoxFor(m => m.EditCandidate.Fname, new { @class ="span3", @placeholder = "Name" }) @*.Class("span2").Placeholder("Name")*@
            @Html.ValidationMessageFor(m => m.EditCandidate.Fname)

            @Html.TextBoxFor(m => m.EditCandidate.Email, new { @class ="span3", @placeholder = "Email" }) @*.Class("span3").Placeholder("Email")*@
            @Html.ValidationMessageFor(m => m.EditCandidate.Email)

            @Html.TextBoxFor(m => m.EditCandidate.ContactNo, new { @class ="span3", @placeholder = "Contact no" }) @*.Class("span2").Placeholder("Contact no")*@
            @Html.ValidationMessageFor(m => m.EditCandidate.ContactNo) 

            @Html.TextBoxFor(m => m.EditCandidate.DateOfBirth, new { @placeholder ="DOB", @class = "span3" }) @*.Format("MM/dd/yyyy").Class("span3").Attr("data-mask", "99/99/9999").Placeholder("DOB")  *@
            @Html.ValidationMessageFor(m => m.EditCandidate.DateOfBirth)

            @Html.TextBoxFor(m => m.EditCandidate.City, new { @class ="span3", @placeholder = "city" }) @*.Class("span2").Placeholder("city")*@
            @Html.ValidationMessageFor(m => m.EditCandidate.City)

            @Html.TextBoxFor(m => m.EditCandidate.Country, new { @class ="span3", @placeholder = "country" }) @*.Class("span2").Placeholder("country")    *@
            @Html.ValidationMessageFor(m => m.EditCandidate.Country)

        <div class="form-inline" >
            
            <label class=" radio" >
                Male  @Html.RadioButtonFor(m => m.EditCandidate.Gender, "Male", new { Checked = "checked" })
            </label>
            <label class="radio">
                Female @Html.RadioButtonFor(m => m.EditCandidate.Gender, "Female")
                                  
            </label>
        </div>
        <div class="modal-footer">
            
            @this.SubmitButton("Save").Class("btn btn-primary")
            @this.Button("Close").Class("btn").Attr("data-dismiss", "modal").Attr("aria-hidden", "true")

        </div>
    </div>
    }
}
else if (Model.EditResume != null)
{
                 using (Html.BeginForm("Edit", "MyProfile", FormMethod.Post, new { Area = "Profile", enctype = "multipart/form-data",id="frmName" }))
                 {
                     <div class="span5">
                         @Html.HiddenFor(m => m.EditResume.Rid)
                         @Html.HiddenFor(m => m.EditResume.MainUser.Mid)
 
                         @Html.TextBoxFor(m => m.EditResume.Photo, new {Type = "file"})
                         @Html.ValidationMessageFor(m => m.EditResume.Photo)

                    
                          <div class="modal-footer">
            
                             @this.SubmitButton("Save").Class("btn btn-primary")
                             @this.Button("Close").Class("btn").Attr("data-dismiss", "modal").Attr("aria-hidden", "true")
                         </div>
                   </div>
                 }
}
else if (Model.EditExperience != null)
{
             using (Html.BeginForm("Edit", "MyProfile", FormMethod.Post, new { Area = "Profile",id="frmName" }))
             {
                 <div class="span5">
                     @Html.HiddenFor(m => m.EditExperience.Eid)
                     @Html.HiddenFor(m => m.EditExperience.MainUser.Mid)
 
                     <div class="form-inline">
                         <label class="radio" Id ="Freshered">
                             Fresher: @Html.RadioButtonFor(m => m.EditExperience.FreExperience, "Fresher", new { Checked = "checked"})
                         </label>
                         <label class="radio" Id ="Experienced">
                             Experience: @Html.RadioButtonFor(m => m.EditExperience.FreExperience, "Experience")
                                  
                         </label>
                     </div>
                     @if (Model.EditExperience.FreExperience =="Experience")
                     {
                         <style>
                              #Experience
                              {
                                   display: initial;
                              }
                         </style>
                     }
                     <div id="Experience">

                         @Html.TextBoxFor(m => m.EditExperience.JobTitle, new {@class = "span4", @placeholder = "Job Title"})  
                         @Html.ValidationMessageFor(m=>m.EditExperience.JobTitle)

                         @Html.DropDownListFor(m => m.EditExperience.ExpYear, new SelectList(eyl.GetExperience(), "value", "name"), "--Select Experience Year--", null)
                         @Html.ValidationMessageFor(m=>m.EditExperience.ExpYear)

                         @Html.DropDownListFor(m => m.EditExperience.ExpMonth, new SelectList(eyl.GetExpMonth(), "value", "name"), "--Select Experience Month--", null)
                         @Html.ValidationMessageFor(m=>m.EditExperience.ExpMonth)

                         @Html.DropDownListFor(m => m.EditExperience.AnnualSalary, new SelectList(eyl.GetAnnualSalary(), "value", "name"), "--Select salary--", null)  
                         @Html.ValidationMessageFor(m=>m.EditExperience.AnnualSalary)

                     </div>
                         @Html.DropDownListFor(m => m.EditExperience.FunctionalArea, new SelectList(eyl.GetFucArea(), "value", "name"), "--Select Function Area--", null)             
                         @Html.ValidationMessageFor(m=>m.EditExperience.FunctionalArea)
   
                     <div class="modal-footer">
                         @this.SubmitButton("Save").Class("btn btn-primary")
                         @this.Button("Close").Class("btn").Attr("data-dismiss", "modal").Attr("aria-hidden", "true")
                    </div>
                 </div>
             }
}
else if (Model.EditEducation != null)
{
          using (Html.BeginForm("Edit", "MyProfile", FormMethod.Post, new { Area = "Profile",id="frmName" }))
          {
              <div class="span5">
                  @Html.HiddenFor(m => m.EditEducation.Eid)
                  @Html.HiddenFor(m => m.EditEducation.MainUser.Mid)
                  @Html.DropDownListFor(m => m.EditEducation.QualificationLevel, new SelectList(eyl.GetQuaLevel(), "value", "name"), "--Select Qualification--", null)    
                  @Html.ValidationMessageFor(m => m.EditEducation.QualificationLevel)

                  @Html.DropDownListFor(m => m.EditEducation.EducationSpecification, new SelectList(eyl.GetEduSpe(), "value", "name"), "--Select Edu Specification --", null)  
                  @Html.ValidationMessageFor(m => m.EditEducation.EducationSpecification)

                  @Html.DropDownListFor(m => m.EditEducation.PassingYear, new SelectList(eyl.GetPassingYear(), "value", "name"), "--Select passing year--", null)  
                  @Html.ValidationMessageFor(m => m.EditEducation.PassingYear)
             
              <div class="modal-footer">
                  @this.SubmitButton("Save").Class("btn btn-primary")
                  @this.Button("Close").Class("btn").Attr("data-dismiss", "modal").Attr("aria-hidden", "true")
              </div>
            </div>
          }
}
else if (Model.EditSkill != null)
{
            using (Html.BeginForm("Edit", "MyProfile", FormMethod.Post, new { Area = "Profile", id="frmName" }))
            {
                <div class="span4">
                 
                    @Html.HiddenFor(m => m.EditSkill.Sid)
                    @Html.HiddenFor(m => m.EditSkill.MainUser.Mid)

                    @Html.TextBoxFor(m => m.EditSkill.SkillTerm, new {@class = "span3", @placeholder = "e.g.php,java,c..etc"})   
                    @Html.ValidationMessageFor(m => m.EditSkill.SkillTerm)

                    @Html.DropDownListFor(m => m.EditSkill.ExpYear, new SelectList(eyl.GetExperience(), "value", "name"), "--Select Exp Year ", null)
                    @Html.DropDownListFor(m => m.EditSkill.ExpMonth, new SelectList(eyl.GetExpMonth(), "value", "name"), "--Select Exp Month ", null)
                <div class="modal-footer">
                 
                  @this.SubmitButton("Save").Class("btn btn-primary")
                  @this.Button("Close").Class("btn").Attr("data-dismiss", "modal").Attr("aria-hidden", "true")
                
                </div>  
         </div>
    }
}         

Areas/Profile/Views/MyProfile/ProfileAccounts.cshtml
@using JobPortal.Core
@using MvcContrib.FluentHtml
@model JobPortal.Web.Areas.Profile.Models.ProfileResume

@{


    ViewBag.Title = "ProfileAccounts";
    Layout = "~/Views/Shared/_Layout.cshtml";
   
    Html.EnableUnobtrusiveJavaScript(false);  
}
<script>
    function changediv() {
        $('#div1').hide();
    }
</script>
<script type="text/javascript">
    $(document).ready(function () {
        BindSpinner();
    });

    function BindSpinner() {
        $("#div_loading").bind("ajaxSend", function () {
            $(this).show();
        }).bind("ajaxStop", function () {
            $(this).hide();
        }).bind("ajaxError", function () {
            $(this).hide();
        });
    };

    $(function() {
        $('#aaaa').click(function() {
            alert("hii");
        });
    });
    function showtitle()
    {
        var s = document.getElementById("aaaa").value;
        
        CallAjax(s);
    }

    function CallAjax(s) {
        $.ajax({
            url: '@Url.Action("ShowMsg", "MyMessage",new {Area = "Profile",Controller="MyMessage"})',
      type: "POST",
      data: { 'title': s },
      success: function (result) {
          $('#AllToMsg').html(result);
          $("#divclass").slideDown();
      }
       
  });
    }
    </script>

<div id="content">
  
    <div id="LefttoRight"> 
        
            <div class="employerHeader employerFont  Post-Padding" >   
                <h3>Change Profile</h3>
            </div>
        <div class="section1 " >
            <ul>
                <li class="li1">
                   <a href="@Url.Action("RegisterProfile","MyProfile")"> MY PROFILE  </a>
                </li>
                <li class="li1">
                   
                    @Ajax.ActionLink("MATCHED JOB","MatchJob","MyProfile",null,new AjaxOptions(){  InsertionMode = InsertionMode.Replace,UpdateTargetId = "div",HttpMethod ="GET",LoadingElementId = "div_loading"})
                </li>
                <li class="li1">
                    @Ajax.ActionLink("APPLIED JOB","ApplyMatchJob","MyProfile",null,new AjaxOptions(){  InsertionMode = InsertionMode.Replace,UpdateTargetId = "div",HttpMethod ="GET",LoadingElementId = "div_loading"})
                </li>
                <li class="li1">
                    @*@Ajax.ActionLink("MESSAGE","Index","MyMessage",new{area="Profile",Controller="MyMessage"},new AjaxOptions(){ InsertionMode = InsertionMode.Replace,UpdateTargetId = "div",HttpMethod ="GET"} )*@
                      @Ajax.ActionLink("MESSAGE","Index","MyMessage",null,new AjaxOptions(){  InsertionMode = InsertionMode.Replace,UpdateTargetId = "div",HttpMethod ="GET",LoadingElementId = "div_loading"})
                </li>
            </ul>
        </div>
        <div id="div" class="section2" >
                
            <div id="div_loading" style="display:none;">
                    <img src="@Url.Content("~/Content/themes/base/images/anim_loading.gif")" alt="" />
            </div>
            @Html.Partial("MatchJob", Model)
       </div>
            
                
           </div>
  </div>
    

Areas/Profile/Views/MyProfile/RegisterCompelete.cshtml
@{
    ViewBag.Title = "registerCompelete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>registerCompelete</h2>