Areas/Job/Controllers/JobApplyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization.Formatters.Binary;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using JobPortal.Core;
using System.Data;
using System.IO;
using JobPortal.Core.Domain.User;
using JobPortal.Core.Repository;
using JobPortal.Web;
using JobPortal.Areas.Job.Models;
using NHibernate.Mapping;

namespace JobPortal.Areas.Job.Controllers
{
    public class JobApplyController : Controller
    {
        //
        // GET: /Search/JobApply/

        private SearchRepository _searchRepository;
        private JobSearchController _jobSearch;
        private JobSearchVM _jobSearchVm;
        private UserRepository _userRepository;
        
        [Authorize]
        public ActionResult UploadResume(int jobId, string companyName)
        {
            HttpCookie cookie = HttpContext.Request.Cookies.Get(FormsAuthentication.FormsCookieName);
            if (cookie != null)
            {
                FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(cookie.Value);
                int candidateId = int.Parse(ticket.Name);

                _searchRepository = new SearchRepository();
                _userRepository = new UserRepository();

                var resume = new ResumeUploadVM();
                resume.ResumeUpload = new ResumeUpload();
                var httpCookie = Request.Cookies.Get("jobid");
                if (httpCookie != null)
                    resume.ResumeUpload.JobId = int.Parse(httpCookie.Value.ToString());

                var dataTable = new DataTable();
                dataTable = _searchRepository.IsResumeAvailable(1, candidateId);
                foreach (DataRow dataRow in dataTable.Rows)
                {
                    var resumeUpload = new ResumeUpload(dataRow);
                    resume.ResumeUpload = resumeUpload;
                    resume.ResumeUpload.JobId = jobId;
                    if (resume.ResumeUpload.FileName != "")
                    {
                        resume.IsResumeAvailable = true;
                    }
                    else
                    {
                        resume.IsResumeAvailable = false;
                    }
                    resume.ResumeUpload.IsUserAvailable = true;
                }
                return PartialView("Test", resume);
            }
            return RedirectToAction("JobDetail", "JobSearch");
        }
        
        [Authorize]
        public virtual PartialViewResult DeleteResume(int jobId, string companyName)
        {
            HttpCookie cookie = HttpContext.Request.Cookies.Get(FormsAuthentication.FormsCookieName);
            if (cookie != null)
            {
                FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(cookie.Value);
                int candidateId = int.Parse(ticket.Name);
                _searchRepository = new SearchRepository();
                _searchRepository.DeleteResume(2, candidateId);
            }
            var resume = new ResumeUploadVM();
            resume.IsResumeAvailable = false;
            Test(jobId, companyName);
            return PartialView("Test");
        }

        /*public ActionResult RetriveFile(int id)
        {
            _searchRepository = new SearchRepository();

            DataTable dt = new DataTable();
            dt = _searchRepository.ResumeRetrive(id);
            MemoryStream ms = new MemoryStream();
            System.Runtime.Serialization.IFormatter formatter = new BinaryFormatter();
            formatter.Serialize(ms, dt);
            byte[] image = null;
            image = ms.ToArray();
            return File(ms,"jpeg");
        }*/

        /*public ActionResult RetriveFile(int id)
        {
            _searchRepository = new SearchRepository();

            DataTable dt = new DataTable();
            dt = _searchRepository.ResumeRetrive(id);
            MemoryStream ms = new MemoryStream();
            System.Runtime.Serialization.IFormatter formatter = new BinaryFormatter();
            formatter.Serialize(ms,dt);
            byte[] image = null;
            image = ms.ToArray();
            
            /*Image _image = Image.FromStream(ms);
            byte[] bt;
            bt = ms.ToArray();
            using (BinaryReader br = new BinaryReader(ms))
            {
                bt = br.ReadBytes((int) ms.Length);
            }
            return new FileContentResult(ms.ToArray(),"Image/Jpge");
            Response.Clear();
            Response.ContentType = "application/pdf";
            Response.AppendHeader("Content-Disposition", "inline;filename=data.pdf");
            Response.BufferOutput = true;
            byte[] pdf;
            _searchRepository = new SearchRepository();
            Response.AppendHeader("Content-Length");
            Response.BinaryWrite(pdf);
            Response.End();
            return View();
            //return _image;
            //ResumeUpload resumeUpload = new ResumeUpload();
            return File(image, "image/png");
        }
        public FileContentResult GetImage(int id)
        {
            _searchRepository = new SearchRepository();

            DataTable dt = new DataTable();
            dt = _searchRepository.ResumeRetrive(id);
            MemoryStream ms = new MemoryStream();
            System.Runtime.Serialization.IFormatter formatter = new BinaryFormatter();
            formatter.Serialize(ms, dt);
            byte[] imageArray = ms.ToArray();
            return new FileContentResult(imageArray, "image/jpeg");
            //Response.ContentType = "image/jpeg";
            //Response.Write(imageArray);
        }*/
        
        [Authorize]
        [ValidateInput(false)]
        public ActionResult ApplyJob(ResumeUpload resumeUpload)
        {
            //if (ModelState.IsValid)
            //{
                HttpCookie cookie = HttpContext.Request.Cookies.Get(FormsAuthentication.FormsCookieName);
                if (cookie != null)
                {
                    FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(cookie.Value);
                    int candidateId = int.Parse(ticket.Name);

                    _searchRepository = new SearchRepository();
                    _userRepository = new UserRepository();
                    _jobSearch = new JobSearchController();
                    Core.Job j = new Core.Job();

                    if (resumeUpload.Photo != null)
                    {
                        string path = @"D:\Temp\";

                        /*if (resumeUpload.Photo.ContentLength > 10240){   
                        ModelState.AddModelError("photo", "The size of the file should not exceed 10 KB");
                        return View();}*/
                        var supportedTypes = new[] {"jpg", "jpeg", "png", "txt", "doc", "pdf"};
                        var extension = System.IO.Path.GetExtension(resumeUpload.Photo.FileName);
                        if (extension != null)
                            resumeUpload.FileExt = extension.Substring(1);
                        resumeUpload.FileName = resumeUpload.Photo.FileName;

                        if (!supportedTypes.Contains(resumeUpload.FileExt))
                        {
                            ModelState.AddModelError("photo","Invalid type. Only the following types (jpg, jpeg, png) are supported.");
                        }
                        resumeUpload.Photo.SaveAs(path + resumeUpload.Photo.FileName);
                        path = resumeUpload.Photo.InputStream.ToString();

                        var target = new MemoryStream();
                        resumeUpload.Photo.InputStream.CopyTo(target);
                        resumeUpload.image = target.ToArray();
                    }

                    if (resumeUpload.user.UserName == null && resumeUpload.Photo == null)
                    {
                        //***********Add only Applied Job*************//
                        resumeUpload.ApplayJob.CandidateId = new MainUser();

                        resumeUpload.ApplayJob.CandidateId.Mid = candidateId;
                        _userRepository.ApplayToJob(resumeUpload);
                    }

                    else if(resumeUpload.IsUserAvailable == true && resumeUpload.user !=null && resumeUpload.Photo == null)
                    {
                        //***********update Candidate Detail*************//
                        resumeUpload.user.CandidateId = new MainUser();
                        resumeUpload.ApplayJob.CandidateId = new MainUser();
                        
                        resumeUpload.ApplayJob.CandidateId.Mid = candidateId;
                        resumeUpload.user.CandidateId.Mid = candidateId;
                        _userRepository.UpdateCandidationInformation(resumeUpload);
                        _userRepository.ApplayToJob(resumeUpload);
                    }

                    else if (resumeUpload.user.UserName == null && resumeUpload.Photo != null)
                    {
                        //***********Update Candidat Resume Only*************//
                        resumeUpload.ApplayJob.CandidateId = new MainUser();
                        resumeUpload.CandidateId = new MainUser();

                        resumeUpload.ApplayJob.CandidateId.Mid = candidateId;
                        resumeUpload.CandidateId.Mid = candidateId;
                        _searchRepository.UploadResume(resumeUpload);
                        _userRepository.ApplayToJob(resumeUpload);
                    }
                    else if(resumeUpload.IsUserAvailable == true && resumeUpload.user.UserName == null && resumeUpload.Photo != null)
                    {
                        //***********Update Candidate Detail and Update Candidate Resume Detail*************//
                        resumeUpload.user.CandidateId = new MainUser();

Areas/Job/Views/JobApply/AppliedJob.cshtml
@{
    ViewBag.Title = "Thank You";
    Layout = "../../../../Views/Shared/_Layout.cshtml";
}

<html>
<head>
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" />
    
</head>
<body>
    <div id="content">
        <h3>Thank you for Applay</h3>
    </div>
</body>
</html>

Areas/Job/Views/JobApply/RetriveFile.cshtml
@using System.Drawing
@model JobPortal.Web.Areas.Search.Models.ResumeUpload
@{
    ViewBag.Title = "RetriveFile";
}
<div>
    <img src="@Model.getimg()"/>
    <img src="@Url.Action("RetriveFile","JobSearch",new {id = 2})" alt="Loading..."/>
</div>

Areas/Job/Views/JobApply/Test.cshtml
@using JobPortal.Core

@using MvcContrib.FluentHtml

@inherits MvcContrib.FluentHtml.ModelWebViewPage<JobPortal.Web.ResumeUploadVM>
              
@{
    Html.EnableUnobtrusiveJavaScript(true);
}
@*@{
    ViewBag.Title = "Upload Resume";
    Layout = "../../../../Views/Shared/_Layout.cshtml";
    if (TempData["User_Id"] != null)
    {
        TempData.Keep();
    }
}*@
<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            $('.ckeditor').CKEDITOR();
        });
            
        $("#Click").click(function () {
            $('#Name').attr("disabled", false);
            $('#Email').attr("disabled", false);
            $('#Contect').attr("disabled", false);
            $('#Location').attr("disabled", false);
        });
    });
</script>

@Html.ValidationSummary(true, "Please correct the errors and try again.")
    @Html.HiddenFor(m => m.ResumeUpload.JobId)
    @Html.HiddenFor(m => m.Job.Emplyer.CompanyName)
    <div id="changeResume">
            @if(Model.ResumeUpload.user != null)            
            {            
                @Html.HiddenFor(m=>m.ResumeUpload.IsUserAvailable)        
                <label id="Warning" class="text-error" style="font-weight: bold">Be Careful If you edit this information this will changed all your earliar applied job</label>        
                        
                <div class="editor-label"><label>Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  : &nbsp;&nbsp;@Html.TextBoxFor(m => m.ResumeUpload.user.UserName, new {@class = "input-large ", disabled = "disabled" ,id="Name"})                          
                                              @Html.ValidationMessageFor(m => m.ResumeUpload.user.UserName)<br/></label></div>
                <div class="editor-label"><label>Email &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : &nbsp;&nbsp; @Html.TextBoxFor(m => m.ResumeUpload.user.Email, new { @class = "input-large", @title = "Enter your Email Login Email to Communicate", disabled = "disabled", id="Email"})
                                              @Html.ValidationMessageFor(m => m.ResumeUpload.user.Email)<br/></label></div>
                <div class="editor-label"><label>Contect &nbsp;&nbsp;&nbsp;                       : &nbsp;&nbsp; @Html.TextBoxFor(m => m.ResumeUpload.user.Contect, new { @class = "input-large", @title = "Enter your Contect number to communicate",disabled = "disabled", id = "Contect"})
                                              @Html.ValidationMessageFor(m => m.ResumeUpload.user.Contect)<br/></label></div>
                <div class="editor-label"><label>Location &nbsp;&nbsp;                            : &nbsp;&nbsp; @Html.TextBoxFor(m => m.ResumeUpload.user.Location, new { @class = "input-large", @title = "Enter your Location", disabled = "disabled", id = "Location"})
                                              @Html.ValidationMessageFor(m => m.ResumeUpload.user.Location)<br/></label></div>
                @Html.HiddenFor(m=>m.ResumeUpload.user.MasteId)
                <input type="button" id="Click" name="Click" value="Click here!" class="btn btn-small btn-warning"/>           
            }            
            else            
            {
                <div class="editor-label"><label>Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  : &nbsp;&nbsp; @Html.TextBoxFor(m => m.ResumeUpload.user.UserName, new { placeholder = "Full Name", @class = "input-large", @title = "Enter your Full Name To Display Employer" })
                                              @Html.ValidationMessageFor(m => m.ResumeUpload.user.UserName)<br/></label></div>
                <div class="editor-label"><label>Email &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : &nbsp;&nbsp; @Html.TextBoxFor(m => m.ResumeUpload.user.Email, new { placeholder = "Add Your@email.com", @class = "input-large", @title = "Enter your Email Login Email to Communicate" })
                                              @Html.ValidationMessageFor(m => m.ResumeUpload.user.Email)<br/></label></div>
                <div class="editor-label"><label>Contect &nbsp;&nbsp;&nbsp;                       : &nbsp;&nbsp; @Html.TextBoxFor(m => m.ResumeUpload.user.Contect, new { placeholder = "Add Contect", @class = "input-large", @title = "Enter your Contect number to communicate" })
                                              @Html.ValidationMessageFor(m => m.ResumeUpload.user.Contect)<br/></label></div>
                <div class="editor-label"><label>Location &nbsp;&nbsp;                            : &nbsp;&nbsp; @Html.TextBoxFor(m => m.ResumeUpload.user.Location, new { placeholder = "Add Location", @class = "input-large", @title = "Enter your Location" })
                                              @Html.ValidationMessageFor(m => m.ResumeUpload.user.Location)<br/></label></div>           
            }
        <div>
            <h5>Company Name &nbsp; : &nbsp; <a style="font: pop-up-menu">                                    
                @{
                    var httpCookieCompanyName = Request.Cookies.Get("companyname");
                    var httpCookieJobId = Request.Cookies.Get("jobid");                                        
                    }
                @if (httpCookieCompanyName != null)  
                {                                                
                    @httpCookieCompanyName.Value                                    
                }                        
            </a></h5>
        </div><hr/>
        <div id="ok">
            <h5>Upload Resume</h5>
            <p>This will attach a resume (max 10MB) if you do not have a profile or if you'd like to use an alternate resume to apply.</p>
            @if (Model.IsResumeAvailable == false)           
            {            
                <div>
                    @Html.TextBoxFor(m => m.ResumeUpload.Photo, new { type = "file" })<br/>
                </div>            
            }
            else            
            {     
                Html.EnableUnobtrusiveJavaScript(false);
                <div>
                    <h5>Your resume is available</h5>
                    <p>@Ajax.ActionLink("ChangeResume", "DeleteResume",new {jobId=1,companyName="Version"},
                                        new AjaxOptions() {UpdateTargetId = "changeResume", HttpMethod = "GET",InsertionMode = InsertionMode.Replace}) This! And Send New Resum</p><br/>
                    <p>Or Apply Send Same Resume</p>
                </div>            
            }
        </div>   
    </div><hr/>            
    <div style="width: 600px">
        <h5>Write Your cover Letter</h5><br/>
        @Html.TextAreaFor(m => m.ResumeUpload.ApplayJob.Coverletter, new { @Class = "ckeditor" })
    </div>

Areas/Job/Views/JobApply/UploadResume.cshtml
@using JobPortal.Core

@inherits MvcContrib.FluentHtml.ModelWebViewPage<JobPortal.Web.ResumeUploadVM>

@{
    ViewBag.Title = "Upload Resume";
    Layout = "../../../../Views/Shared/_Layout.cshtml";
    if (TempData["User_Id"] != null)
    {
        TempData.Keep();
    }
}
@*<html id="testing" class="Post-Padding modal hide fade" tabindex="-1" role="dialog">
    <head>*@
        <script type="text/javascript">
            $(document).ready(function () {
                $(function () {
                    $('.ckeditor').CKEDITOR();
                });
            
                $("#Click").click(function () {
                    $('#Name').attr("disabled", false);
                    $('#Email').attr("disabled", false);
                    $('#Contect').attr("disabled", false);
                    $('#Location').attr("disabled", false);
                });
            });
        </script>
    @*</head>
    <body>*@
        <div id ="myModal" class="modal hide fade" tabindex="-1" role="dialog">
        <div id="content" class="Post-Padding" style="width: 908px">@*<h1>@Model.User.MasteId</h1>*@
            @Html.ValidationSummary(true, "Please correct the errors and try again.")
            @using (Html.BeginForm("ApplyJob", "JobApply", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                
                @Html.HiddenFor(m => m.ResumeUpload.JobId)
                
                @*@Html.HiddenFor(m => m.Job.Emplyer.CompanyName)
                @Html.Hidden("HiddenField", Model.Job.Id)*@
                
                <div>
                    <fieldset>
                        <legend>Application Information</legend>
                        <h5>About You</h5>
                        @if(Model.ResumeUpload.user != null)
                        {
                            @Html.HiddenFor(m=>m.ResumeUpload.IsUserAvailable)
                            <label id="Warning">Be Careful If you edit this information this will changed all your earliar applied job</label>
                            <div class="editor-label"><label>Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  : &nbsp;&nbsp;@Html.TextBoxFor(m => m.ResumeUpload.user.UserName, new {@class = "input-large ", disabled = "disabled" ,id="Name"})
                                                          @Html.ValidationMessageFor(m => m.ResumeUpload.user.UserName)<br/></label></div>
                            <div class="editor-label"><label>Email &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : &nbsp;&nbsp; @Html.TextBoxFor(m => m.ResumeUpload.user.Email, new { @class = "input-large", @title = "Enter your Email Login Email to Communicate", disabled = "disabled", id="Email"})
                                                          @Html.ValidationMessageFor(m => m.ResumeUpload.user.Email)<br/></label></div>
                            <div class="editor-label"><label>Contect &nbsp;&nbsp;&nbsp;                       : &nbsp;&nbsp; @Html.TextBoxFor(m => m.ResumeUpload.user.Contect, new { @class = "input-large", @title = "Enter your Contect number to communicate",disabled = "disabled", id = "Contect"})
                                                          @Html.ValidationMessageFor(m => m.ResumeUpload.user.Contect)<br/></label></div>
                            <div class="editor-label"><label>Location &nbsp;&nbsp;                            : &nbsp;&nbsp; @Html.TextBoxFor(m => m.ResumeUpload.user.Location, new { @class = "input-large", @title = "Enter your Location", disabled = "disabled", id = "Location"})
                                                          @Html.ValidationMessageFor(m => m.ResumeUpload.user.Location)<br/></label></div>
                            @Html.HiddenFor(m=>m.ResumeUpload.user.MasteId)
                                 @*@Html.DropDownListFor(m=>m.User.Location,new SelectList(list,"name"),"Select Location")
                                    @this.Html.DropDownListFor(m=>m.User.Location,new SelectList(list,"name"),"Select Location")*@
                            <input type="button" id="Click" name="Click" value="Click here!" class="btn btn-small btn-warning"/>
                        }
                        else
                        {
                            <div class="editor-label"><label>Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  : &nbsp;&nbsp; @Html.TextBoxFor(m => m.ResumeUpload.user.UserName, new { placeholder = "Full Name", @class = "input-large", @title = "Enter your Full Name To Display Employer" })
                                                          @Html.ValidationMessageFor(m => m.ResumeUpload.user.UserName)<br/></label></div>
                            <div class="editor-label"><label>Email &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : &nbsp;&nbsp; @Html.TextBoxFor(m => m.ResumeUpload.user.Email, new { placeholder = "Add Your@email.com", @class = "input-large", @title = "Enter your Email Login Email to Communicate" })
                                                          @Html.ValidationMessageFor(m => m.ResumeUpload.user.Email)<br/></label></div>
                            <div class="editor-label"><label>Contect &nbsp;&nbsp;&nbsp;                       : &nbsp;&nbsp; @Html.TextBoxFor(m => m.ResumeUpload.user.Contect, new { placeholder = "Add Contect", @class = "input-large", @title = "Enter your Contect number to communicate" })
                                                          @Html.ValidationMessageFor(m => m.ResumeUpload.user.Contect)<br/></label></div>
                            <div class="editor-label"><label>Location &nbsp;&nbsp;                            : &nbsp;&nbsp; @Html.TextBoxFor(m => m.ResumeUpload.user.Location, new { placeholder = "Add Location", @class = "input-large", @title = "Enter your Location" })
                                                          @Html.ValidationMessageFor(m => m.ResumeUpload.user.Location)<br/></label></div>
                        }
                    </fieldset>
                    <div>
                        <h5>Company Name &nbsp; : &nbsp; <a style="font: pop-up-menu">
                                                             @{
                                                                 var httpCookieCompanyName = Request.Cookies.Get("companyname");
                                                                 var httpCookieJobId = Request.Cookies.Get("jobid");
                                                             }
                                                             @if (httpCookieCompanyName != null)
                                                             {
                                                                 @httpCookieCompanyName.Value.ToString()
                                                             }
                                                         </a></h5>
                    </div><hr/>
                    <div>
                        <h5>Upload Resume</h5>
                                
                        <p>This will attach a resume (max 10MB) if you do not have a profile or if you'd like to use an alternate resume to apply.</p>
                                
                        @if (Model.IsResumeAvailable == false)
                        {
                            <div>
                                @Html.TextBoxFor(m => m.ResumeUpload.Photo, new { type = "file" })
                                <br/><br/>
                            </div>
                        }
                        else
                        {
                            <div><br/>
                                <h5>Your resume is available</h5>
                                <p>@Html.ActionLink("Change", "DeleteResume",new {jobId = int.Parse(httpCookieJobId.Value.ToString()),companyName = httpCookieCompanyName.Value.ToString()}) This! And Send New Resum</p>
                                @*<img src="@Model.getimg()"/>*@

                                @*<img src="@Url.Action("RetriveFile","JobApply",new {cid = 3}) />*@
                                <br/>
                                <p>Or Apply Send Same Resume</p><br/>
                            </div>
                        }
        
                    </div>   
                </div><hr/>
                <div style="width: 600px">
                    <h5>Write Your cover Letter</h5><br/>
                    @Html.TextAreaFor(m => m.ResumeUpload.ApplayJob.Coverletter, new { @Class = "ckeditor" })
                </div><hr/>
                
                <input type="submit" value="Apply" class="btn btn-success"/>
            }
        </div>
        </div>
    @*</body>
</html>*@